name: CI
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: production
    steps:
    - uses: actions/checkout@v3
    - name: Set node version
      run: echo "NODE_VERSION=`cat .nvmrc`" >> $GITHUB_ENV
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm i
    - run: npm run build
    - run: npm run lint